/*
 * Copyright 2019 Christophe Marchand
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *     http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package top.marchand.oxygen.maven.project.support.impl;

import ro.sync.exml.workspace.api.PluginWorkspace;

/**
 *
 * @author cmarchand
 */
public class MavenOptionView extends javax.swing.JPanel {

    private final PluginWorkspace pluginWorkspace;
    
    public MavenOptionView(PluginWorkspace pluginWorkspace) {
        super();
        this.pluginWorkspace = pluginWorkspace;
        initComponents();
    }
    
    public void setMavenInstallDir(String location) {
        dfMavenInstallDir.setText(location);
    }
    
    public void setLocalRepositoryLocation(String location) {
        dfLocalRepoLocation.setText(location);
    }
    
    public String getMavenInstallDir() {
        return dfMavenInstallDir.getText();
    }
    
    public String getLocalRepositorLocation() {
        return dfLocalRepoLocation.getText();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMavenDir = new javax.swing.JLabel();
        dfMavenInstallDir = new javax.swing.JTextField();
        pbChooseDir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        dfLocalRepoLocation = new javax.swing.JTextField();
        pbChooseRepo = new javax.swing.JButton();

        lblMavenDir.setText("Maven install directory");

        pbChooseDir.setText("...");
        pbChooseDir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pbChooseDirActionPerformed(evt);
            }
        });

        jLabel1.setText("Local repository location");

        pbChooseRepo.setText("...");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(lblMavenDir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dfMavenInstallDir, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
                    .addComponent(dfLocalRepoLocation))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pbChooseRepo, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pbChooseDir, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMavenDir)
                    .addComponent(dfMavenInstallDir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pbChooseDir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(dfLocalRepoLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pbChooseRepo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void pbChooseDirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pbChooseDirActionPerformed
        // TODO
    }//GEN-LAST:event_pbChooseDirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField dfLocalRepoLocation;
    private javax.swing.JTextField dfMavenInstallDir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblMavenDir;
    private javax.swing.JButton pbChooseDir;
    private javax.swing.JButton pbChooseRepo;
    // End of variables declaration//GEN-END:variables
}
